---
apiVersion: v1
kind: Pod
metadata:
  name: tls-dashboard
  namespace: devops
spec:
  restartPolicy: OnFailure
  volumes:
  - name: tls-dashboard
    nfs:
      server: 192.168.10.245
      path: /data
  containers:
  - name: nginx
    image: nginx:1.12
    volumeMounts:
    - name: tls-dashboard
      mountPath: /usr/share/nginx/html
    ports:
    - name: web
      containerPort: 80
  - name: tlsnode
    image: bluerdocker/tls-dashboard:v1
    volumeMounts:
    - name: tls-dashboard
      mountPath: /pod-data