---
apiVersion: v1
kind: Pod
metadata:
  name: tls-dashboard
  namespace: devops
spec:
  restartPolicy: OnFailure
  volumes:
  - name: tls-dashboard
    nfs:
      server: 192.168.10.247
      path: /var/lib/docker/tls-dashboard
  containers:
  - name: nginx
    image: nginx:1.12
    volumMounts:
    - name: tls-dashboard
      mountPath: /usr/share/nginx/html
    ports:
    - name: web
      containerPort: 80
  - name: tlsnode
    image: bluerdocker/mynode:latest
    volumeMounts:
    - name: tls-dashboard
      mountPath: /pod-data
    command: ["/bin/bash","-c","--"]
    args: ["while true; do sleep 300; done"]

    

