---
apiVersion: v1
kind: Pod
metadata:
  name: tls-dashboard
spec:
  restartPolicy: Never
  volumes:
  - name: shard-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx:1.12
    volumMounts:
    - name: shard-data
      mountPath: /usr/share/nginx/html
    ports:
    - name: web
      containerPort: 80
      hostIP: 192.168.10.248
      hostPort: 10090
  - name: tlsnode
    image: bluerdocker/mynode:latest
    volumeMounts:
    - name: shard-data
      mountPath: /pod-data
    command: ["/bin/bash","-c","--"]
    args: ["while true; do sleep 300; done"]

    

